spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_services
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off
  application:
    name: register-service
server:
  port: 8090

client:
  feign:

    user-service:
      path: http://localhost:8082/user
      extractRoleFromToken: /extract/role
      extractSellerNameFromToken: /extract/seller-name
